### ISSUE TITLE
[monitor] all account state on each block/epoch

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/monitor#14]
As requested by Sahil, we need to keep monitoring and keep track of all account state rewards earned by delegators.  Vlad had added an RPC call in this PR (https://github.com/harmony-one/harmony/pull/2254/files) to get all accounts in each block from the explorer node, and thus we can keep track of the account state.  Need to save the account info into a file or a db.

**Comment by rhazberries** [comment]
@LeoHChen This seems to be tracked by Yishuang's ONE holder page.
